import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import SystemProvider from "@/components/providers/system-provider";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${interSans.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SystemProvider>
            <SidebarProvider>
              <AppSidebar />
              <main className="flex-1 min-w-0 relative">
                <div className="w-full p-2 bg-background absolute top-0 left-0 right-0 z-10">
                  <SidebarTrigger className="cursor-pointer" />
                </div>
                <div className="h-screen font-sans dark:bg-zinc-900 flex-1 px-20 pt-24 overflow-y-auto">
                  {children}
                </div>
              </main>
              <Toaster />
            </SidebarProvider>
          </SystemProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
